baseURL = "https://rockartist33.github.io/T-Level-Revision-dpdd/"
languageCode = "en-us"
googleAnalytics = "G-XYFD95KB4J"
relativeURLs = true
disablePathToLower = true
ignoreFiles = [
    "/content/templates/*",
    "/content/private/*",
]
summaryLength = 50
paginate = 20
enableGitInfo = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = true
        anchorLineNos = true
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        lastmod = ["lastmod", ":git", "date", "publishDate"]
        publishDate = ["publishDate", "date"]
    [markup.goldmark.renderer]
        unsafe = true
